//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoliCap {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResSoli {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResSoli() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoliCap.ResSoli", typeof(ResSoli).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Commit VQ 的本地化字符串。
        /// </summary>
        internal static string ColumnCommitVQ {
            get {
                return ResourceManager.GetString("ColumnCommitVQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Usage 的本地化字符串。
        /// </summary>
        internal static string ColumnCPU_Usage {
            get {
                return ResourceManager.GetString("ColumnCPU_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit Time 的本地化字符串。
        /// </summary>
        internal static string ColumnExitTime {
            get {
                return ResourceManager.GetString("ColumnExitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Location 的本地化字符串。
        /// </summary>
        internal static string ColumnFile {
            get {
                return ResourceManager.GetString("ColumnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free VQ 的本地化字符串。
        /// </summary>
        internal static string ColumnFreeVQ {
            get {
                return ResourceManager.GetString("ColumnFreeVQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peak PF 的本地化字符串。
        /// </summary>
        internal static string ColumnPeakPF {
            get {
                return ResourceManager.GetString("ColumnPeakPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peak VQ 的本地化字符串。
        /// </summary>
        internal static string ColumnPeakVQ {
            get {
                return ResourceManager.GetString("ColumnPeakVQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peak WS 的本地化字符串。
        /// </summary>
        internal static string ColumnPeakWS {
            get {
                return ResourceManager.GetString("ColumnPeakWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page File 的本地化字符串。
        /// </summary>
        internal static string ColumnPF {
            get {
                return ResourceManager.GetString("ColumnPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Name 的本地化字符串。
        /// </summary>
        internal static string ColumnProcessName {
            get {
                return ResourceManager.GetString("ColumnProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse VQ 的本地化字符串。
        /// </summary>
        internal static string ColumnReverseVQ {
            get {
                return ResourceManager.GetString("ColumnReverseVQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Time 的本地化字符串。
        /// </summary>
        internal static string ColumnStartTime {
            get {
                return ResourceManager.GetString("ColumnStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VQ 的本地化字符串。
        /// </summary>
        internal static string ColumnVQ {
            get {
                return ResourceManager.GetString("ColumnVQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wasted VQ 的本地化字符串。
        /// </summary>
        internal static string ColumnWastedVQ {
            get {
                return ResourceManager.GetString("ColumnWastedVQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work Set 的本地化字符串。
        /// </summary>
        internal static string ColumnWS {
            get {
                return ResourceManager.GetString("ColumnWS", resourceCulture);
            }
        }
    }
}
